# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(662, 338)
        MainWindow.setInputMethodHints(QtCore.Qt.ImhNone)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.acronymList = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.acronymList.setGeometry(QtCore.QRect(10, 90, 631, 201))
        self.acronymList.setAutoFillBackground(False)
        self.acronymList.setInputMethodHints(QtCore.Qt.ImhNone)
        self.acronymList.setTabChangesFocus(False)
        self.acronymList.setReadOnly(True)
        self.acronymList.setObjectName("acronymList")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 101, 17))
        self.label.setObjectName("label")
        self.acronymText = QtWidgets.QTextEdit(self.centralwidget)
        self.acronymText.setGeometry(QtCore.QRect(10, 30, 111, 31))
        self.acronymText.setMouseTracking(False)
        self.acronymText.setInputMethodHints(QtCore.Qt.ImhNone)
        self.acronymText.setObjectName("acronymText")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 662, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Exit = QtWidgets.QAction(MainWindow)
        self.action_Exit.setObjectName("action_Exit")
        self.action_About = QtWidgets.QAction(MainWindow)
        self.action_About.setObjectName("action_About")
        self.menuFile.addAction(self.action_About)
        self.menuFile.addAction(self.action_Exit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.acronymText, self.acronymList)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Acronym Finder"))
        self.label.setText(_translate("MainWindow", "Enter acronym:"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.action_Exit.setText(_translate("MainWindow", "&Exit"))
        self.action_About.setText(_translate("MainWindow", "&About"))
